APP:
  NAME: ginweibo
  RUNMODE: debug
  Port: :8088
  URL: http://localhost:8088 # 网站 url，内部跳转时会用到该项
  KEY: base64:O+VQ74YEigLPDzLKnh2HW/yjCdU2ON9v7xuKBgSOEAo=
  ENABLE_CSRF: true 

DB:
  CONNECTION: mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: ginweibo
  USERNAME: root
  PASSWORD: 123456

MAIL:
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.qq.com 
  MAIL_PORT: 465 
  MAIL_USERNAME: 184322994@qq.com
  MAIL_PASSWORD: vgvojkjxoerpbidi # 授权码或密码
  MAIL_FROM_NAME: ginweibo # 邮件发送者名称
